### ISSUE TITLE
Laravel integration

### ISSUE THREAD

**Issue by gauravtiwari** [jasonhinkle/phreeze#101]
Hey Jason,

I was wondering about integrating phreeze with Laravel 4. How is it structured to be integrated with Laravel 4 framework? Or is it standalone PHP framework?

Please let me know. Thank you

Gaurav

**Comment by boussou** [comment]
@jasonhinkle is very polite, but IMHO there is no reason to do so. Phreeze has its logic, and provides the same fonctionnalities. So it is a "competitor". 
Using Blade would be useless here, as Phreeze brilliantly generates client clode (JS/underscore) and Blade is just a "me too" version of so many predecessors. 
Eloquent? why not, but it you look at the phreeze logic, it does not mimic other frameworks but implements the ORM paradigm with unusual design patterns. It is verbose, but maybe more maintainable and less error prone IMHO. besides, who cares? it is scaffolded.

The only thing that could be ported to Laravel is the Phreeze's brilliant client code scaffolding. 
And that would be gentle "idea" stealing because it is its main differentiator.
