### ISSUE TITLE
BLOB

### ISSUE THREAD

**Issue by rodrigorojas** [jasonhinkle/phreeze#216]
Excuse me... Anyone can help me to solve my problem?

I have implemented an audio recoder phreeze applicattion using html audio getUserMedia to save blob mpeg/mp3 data on my database. Work perfectly and Im sending large data using one external class...tested and working perfectly. Some of my others applications can decode/enconde this data and I can "listen" audio files decoded from my blob data on my database.

But, when I call my application to query data, the phreeze dont render the page... only show the blue loading bar...

Thanks for any help.

regards from brazil

RR

**Comment by Esysc** [comment]
Coule give more détails? For example analyze the GET request and see if JavaScript error on console appears. What data do you expect to render?

**Comment by jasonhinkle** [comment]
If you have large blobs in your DB - you may need to create a "reporter" class when you are querying only the non-blob fields - otherwise they're being read from the DB into PHP memory which would probably cause the page to hang.

If you are saving blobs, the best way to do it is have the file meta-data in one table and the actual blob data in a separate table where you are careful to only query 1 record at a time when the file is requested.

**Comment by rodrigorojas** [comment]
thx a lot  @jasonhinkle 

My blob data storage is separately from phreeze app database. working fine now
