### ISSUE TITLE
Is there a list of sites or complete applications build on Phreeze?

### ISSUE THREAD

**Issue by sumith** [jasonhinkle/phreeze#217]
I've been getting mixed information regarding these frameworks.  Some say these only help with simple applications and for any complex applications these always hit a roadblock and you should start from scratch !!

Is there a list of sites or applications that are build using Phreeze?

**Comment by jasonhinkle** [comment]
It's a good idea to question whether any tool is the right one for your project.  I'd like to think that Phreeze is fairly unobtrusive and is more of a way of organizing your code, rather than a "system" that you have to work within. The builder is just there to save you time writing the boring stuff. It's meant as a starting point, but if your app is going to grow then you have to invest the time to learn the framework and not rely on the generated code.

As for sites, I don't keep track of them but two fairly large systems that were built using phreeze are eventric.com and liftopia.com (1.0). My previous consulting company built many applications using phreeze, some simple and some complicated. The framework was designed for building applications of any size.

**Comment by sumith** [comment]
Thanks @jasonhinkle .  I've been working with Phreeze for a few months now and find the builder to be super useful.  However I'm not a full time developer and have a hard time debugging php.  So have been trying to get someone build pieces of the product I'm looking to build.

Appreciate your feedback and time.

**Comment by mihaadzic** [comment]
Hi!

If you checkout https://www.timecase.net/ you'll find it was built using phreeze. I asked the developer for one simple thing that is to add a column to one of the database tables. Answer was, they don't do custom codes because it takes too much time to do it. It is a nice Time Tracking app tho. I do like it but, like I said i would need to add a column and be able to display and edit that column.

If you find a way to do that maybe let me know. :)

**Comment by boussou** [comment]
looking at the video here it is certain
https://www.youtube.com/watch?v=R5UE0IJdI00

**Comment by Esysc** [comment]
My app is on top of phreeze butunfortunately  is not available outside corporate. I could say that this app manage bare metal and network provisioning aix linux windows environment,this just to show how widely you can emploi this framework. May be something better is behind the corner then

**Comment by Esysc** [comment]
It s up to you decide what will work better or will be easier to master
