### ISSUE TITLE
Database Keys

### ISSUE THREAD

**Issue by Denace** [jasonhinkle/phreeze#224]
Hi Jason, hope you are well. i'd like to ask what the reason is for phreeze not supporting compound keys by default. Additionally whether it is advisable to override that default behaviour and if so how to override it.

**Comment by jasonhinkle** [comment]
Basically I just didn't implement it because it's tricky to generate the maps and controllers for tables that don't have a unique primary key. But I'm totally open to solutions.

There's really nothing stopping Phreeze itself from working with the table - it's just the builder that doesn't generate the code for them. One solution you can do is to just remove one key temporarily and generate the code, then add your key back in. Then you'd just have to add your validation and retrieval login in the controller, which wouldn't be that tough.

**Comment by Denace** [comment]
thanks will do
